project_id = "gbddbubzvhmgnwyowucd"

[functions.inventory_insights]
verify_jwt = false

[functions.generate_forecast]
verify_jwt = false

[functions.generate_schedule]
verify_jwt = false

[functions.process_stripe_payment]
verify_jwt = false